import os

ROOT_DIR = os.path.dirname((__file__))
PACKAGES_DIR = "d3b_ingest_packages/packages"

INGEST_PROCESS_USER = os.getenv("FLY_POSTGRES_INGEST_USER")
INGEST_PROCESS_PASSWORD = os.getenv("FLY_POSTGRES_INGEST_PASSWORD")
INGEST_VIEWER_USER = os.getenv("FLY_POSTGRES_VIEWER_USER")
INGEST_VIEWER_PASSWORD = os.getenv("FLY_POSTGRES_VIEWER_PASSWORD")
